---
deployment:
  tasks:
    - export DEPLOYPATH=/home/modjiemediguesth/public_html/
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH 2>/dev/null || :
    - /bin/cp robots.txt $DEPLOYPATH 2>/dev/null || :
    - /bin/cp sitemap.xml $DEPLOYPATH 2>/dev/null || :
    - /bin/cp google*.html $DEPLOYPATH 2>/dev/null || :
